### ISSUE TITLE
[Usability Issue] Please account for Graphite Accent when using Dark Mode

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/storybook-packager-public#39]
<img width="661" alt="image" src="https://user-images.githubusercontent.com/237349/82582515-ceab1500-9b57-11ea-8142-fea433f9fb76.png">

When using dark mode and a graphite accent color It is not possible to see what is selected by skimming just the page/section list.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/237349/82582604-f0a49780-9b57-11ea-8f07-8ea949911205.png">

**Comment by Lin87** [comment]
The unselected color is now black, which works for both light and dark mode. The selected item's border color will change to whatever the system hightlight color is set as. Reasoning for black: because graphite is gray and changing the border to different shades of gray could cause further confusion on which item is selected.

Pending to be release in next build (27)....
